<?php

use Illuminate\Database\Seeder;

class SkillCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'name' => 'Armadura·Ligera',
                'code' => 'ArdL',
                'stats' => 'Ag/Fu/Ag',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armadura·Media',
                'code' => 'ArdM',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armadura·Pesada',
                'code' => 'ArdP',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·2manos',
                'code' => 'Arm2M',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Arrojadizas',
                'code' => 'ArmAj',
                'stats' => 'Ag/Fu/Ag',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Artilleria',
                'code' => 'ArmAt',
                'stats' => 'In/Ag/Ra',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Contundentes',
                'code' => 'ArmC',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Asta',
                'code' => 'ArmAs',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Filo',
                'code' => 'ArmF',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Armas·Proyectiles',
                'code' => 'ArmPr',
                'stats' => 'Ag/Fu/Ag',
                'progression' => 'standard',
                'is_sortable' => '1',
                'is_editable' => '0',
            ],
            [
                'name' => 'Arte·Activo',
                'code' => 'ArtA',
                'stats' => 'Pr/Em/Ag',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Arte·Pasivo',
                'code' => 'ArtP',
                'stats' => 'Em/In/Pr',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Artes Marciales·Barridos',
                'code' => 'AmB',
                'stats' => 'Ag/Fu/Fu',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Artes Marciales·Golpes',
                'code' => 'AmG',
                'stats' => 'Fu/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Artes Marciales·Maniobras de Combate',
                'code' => 'AmMC',
                'stats' => 'Ag/Rp/Ag',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Ataques Especiales',
                'code' => 'AtaEsp',
                'stats' => 'Fu/Ag/Ad',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Atletismo·Gimnasia',
                'code' => 'AtlG',
                'stats' => 'Ag/Rp/Ag',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Atletismo·Potencia',
                'code' => 'AtlP',
                'stats' => 'Fu/Co/Ag',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Atletismo·Resistencia',
                'code' => 'AtlR',
                'stats' => 'Co/Ag/Fu',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Autocontrol',
                'code' => 'Autoc',
                'stats' => 'Ad/Pr/Ad',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Ciencia/Analitica·Basica',
                'code' => 'CienB',
                'stats' => 'Ra/Me/Ra',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Ciencia/Analitica·Especializada',
                'code' => 'CienE',
                'stats' => 'Ra/Me/Ra',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Comunicacion',
                'code' => 'Comun',
                'stats' => 'Ra/Me/Em',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Conocimiento·General',
                'code' => 'ConGen',
                'stats' => 'Me/Ra/Me',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Conocimiento·Magico',
                'code' => 'ConMag',
                'stats' => 'Me/Ra/Me',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Conocimiento·Oscuro',
                'code' => 'ConOsc',
                'stats' => 'Me/Ra/Me',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Conocimiento·Tecnico',
                'code' => 'ConTec',
                'stats' => 'Me/Ra/Me',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Defensas Especiales',
                'code' => 'DefEsp',
                'stats' => 'Ninguna',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Desarrollo de Puntos de Poder',
                'code' => 'DesPP',
                'stats' => '*',
                'progression' => 'special',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Desarrollo Fisico',
                'code' => 'DesFis',
                'stats' => 'Co/Ad/Co',
                'progression' => 'special',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Exteriores·Animales',
                'code' => 'ExtAni',
                'stats' => 'Em/Ag/Em',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Exteriores·Entorno',
                'code' => 'ExtEnt',
                'stats' => 'Ad/In/Me',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Hechizos Dirigidos',
                'code' => 'HecDir',
                'stats' => 'Ag/Ad/Ag',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Basicas de Hechizos',
                'code' => 'ListBas',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Abiertas de Hechizos',
                'code' => 'ListAb',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Cerradas de Hechizos',
                'code' => 'ListCerr',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Basicas de Otras Profesiones',
                'code' => 'ListBasOt',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Abiertas de Otros Reinos',
                'code' => 'ListAbOt',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Cerradas de Otros Reinos',
                'code' => 'ListCerrOt',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Basicas de Otros Reinos',
                'code' => 'ListBasOtR',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Abiertas Arcanas',
                'code' => 'ListAbArc',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Hechizos de Adiestramiento',
                'code' => 'ListAd',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Hechizos de Adiestramientos de Otros Reinos',
                'code' => 'ListAdOtR',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Basicas de la Triada',
                'code' => 'ListTri',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Listas Basicas Elementales Complementarias',
                'code' => 'ListElCom',
                'stats' => '*',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Influencia',
                'code' => 'Infl',
                'stats' => 'Pr/Em/In',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Maniobras de Combate',
                'code' => 'ManCom',
                'stats' => 'Ag/Rp/Ad',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Manipulacion del Poder',
                'code' => 'ManPod',
                'stats' => 'Em/In/Ad',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Oficios',
                'code' => 'Ofi',
                'stats' => 'Ag/Me/Ad',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Percepcion·Busqueda',
                'code' => 'PerBus',
                'stats' => 'In/Ra/Ad',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Percepcion·Perspicacia',
                'code' => 'PerPers',
                'stats' => 'In/Ad/In',
                'progression' => 'limited',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Percepcion·Sentidos',
                'code' => 'PerSen',
                'stats' => 'In/Ad/In',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Percepcion de Poder',
                'code' => 'PerPod',
                'stats' => 'Em/In/Pr',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Subterfugio·Ataque',
                'code' => 'SubAta',
                'stats' => 'Ag/Ad/In',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Subterfugio·Mecanica',
                'code' => 'SubMec',
                'stats' => 'In/Ag/Ra',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Subterfugio·Sigilo',
                'code' => 'SubSig',
                'stats' => 'Ag/Ad/In',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Tecnica/Comercio·General',
                'code' => 'TecGen',
                'stats' => 'Ra/Me/Ad',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Tecnica/Comercio·Profesional',
                'code' => 'TecPro',
                'stats' => 'Ra/Me/In',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Tecnica/Comercio·Vocacional',
                'code' => 'TecVoc',
                'stats' => 'Me/In/Ra',
                'progression' => 'combined',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
            [
                'name' => 'Urbana',
                'code' => 'Urb',
                'stats' => 'In/Pr/Ra',
                'progression' => 'standard',
                'is_sortable' => '0',
                'is_editable' => '0',
            ],
        ];
        DB::table('skill_categories')->insert($data);
    }
}
