---

# OpenRPG Development docker-compose
# For those who cannot afford wasting time on installing packages

version: '3'

services:
  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DATABASE: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
